/**
 * JavaCC template file created by SF JavaCC plugin 1.5.28+ wizard for JavaCC 1.5.0+
 */
options
{
  static = false;
}

PARSER_BEGIN(AwesomeGrammar)
package com.github.jeandersonbc.javacclabs.parser;
import java.lang.*;

public class AwesomeGrammar
{
  public void parse()
  {
    throw new RuntimeException("Not implemented yet!");
  }
}

PARSER_END(AwesomeGrammar)

SKIP :
{
  " "
| "\r"
| "\t"
| "\n"
}
